# Generated by Django 5.2.5 on 2025-10-13 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_file_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
