# Generated by Django 5.2.5 on 2025-10-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_alter_file_updated_at_alter_file_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecategorymapping',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-13 12:00'),
            preserve_default=False,
        ),
    ]
