# Generated by Django 5.2.5 on 2025-10-13 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_filecategorymapping_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecategorymapping',
            name='reassigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filecategorymapping',
            name='reassigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filecategorymapping',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mappings', to=settings.AUTH_USER_MODEL),
        ),
    ]
