# Generated by Django 5.2.5 on 2025-10-13 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_filecategorymapping_reassigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecategorymapping',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filecategorymapping',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filecategorymapping',
            name='reassigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
